# Timeout in seconds that Limine will use before automatically booting.
timeout: 0

# The entry name that will be displayed in the boot menu
/PxttpOS
    # Change the protocol line depending on the used protocol.
    protocol: limine
    kaslr:no
    # Path to the kernel to boot. boot():/ represents the partition on which limine.cfg is located.
    kernel_path: boot():/kernel.elf
    resolution: 1280x720x32
    module_path: boot():/boot.mbif
    # module_path: boot():/background.mbif
    # module_path: boot():/MButton.mbif
    # module_path: boot():/MButton_S.mbif
    # module_path: boot():/mouse.mbzf
    # module_path: boot():/test.mbif
    # module_path: boot():/window_buttons.mbzf
    # module_path: boot():/window_icons.mbzf
    module_path: boot():/zap-light16.psf
    module_path: boot():/programs.saf
    # module_path: boot():/maab.mbzf
    # module_path: boot():/other.mbzf
    # module_path: boot():/test.elf
    # module_path: boot():/nothing-doer.elf
    
