.TH LIMINE 1 "version 8.0.12" "September 2024"
.SH NAME
limine \- Multiplexer to several Limine-related utilities.
.SH SYNOPSIS
.B limine
.RI "<command> <args...>"
.SH DESCRIPTION
\fBlimine\fR provides a series of Limine-related utilities condensed in a single executable.
.SH BUGS
Please report bugs via
.IR https://github.com/limine-bootloader/limine/issues .
.SH HOMEPAGE
.I https://limine-bootloader.org/
